### ISSUE TITLE
Refactor no-expect-in-setup-teardown, missing-expect and no-global-setup rules to not violate DRY

### ISSUE THREAD

**Issue by alecxe** [tlvince/eslint-plugin-jasmine#108]
[`no-expect-in-setup-teardown`](https://github.com/tlvince/eslint-plugin-jasmine/blob/master/lib/rules/no-expect-in-setup-teardown.js) and [`missing-expect`](https://github.com/tlvince/eslint-plugin-jasmine/blob/master/lib/rules/missing-expect.js) share the same `buildName` function.

[`no-expect-in-setup-teardown`](https://github.com/tlvince/eslint-plugin-jasmine/blob/master/lib/rules/no-expect-in-setup-teardown.js) and [`no-global-setup`](https://github.com/tlvince/eslint-plugin-jasmine/blob/master/lib/rules/no-global-setup.js) share the same regular expression for the setup/teardown regular expression pattern.

It would be a good idea to not violate DRY principle and extract the common parts into a reusable library/configuration module.

**Comment by DianaSuvorova** [comment]
looks like a straightforward change to me. I will add helpers module move `buildName` and other helpers (`no-dupes` and `prohibit`) in there.

**Comment by DianaSuvorova** [comment]
@burabure, since the branch got merged should we close this? And by we I mean you, I don't have permissions 😄

**Comment by burabure** [comment]
:+1:

**Comment by burabure** [comment]
btw @DianaSuvorova, you've been making some most needed contributions, are you interested in being a mantainer?

**Comment by DianaSuvorova** [comment]
Yeah, I'd be happy to!

Here is the question - what is the strategy to advance the version of the library?  
I am planning to address few more issues/ features requested here and do a minor release.

**Comment by burabure** [comment]
@tlvince ping ^^^^

**Comment by tlvince** [comment]
@burabure sorry for missing this. Thanks for your continued work with maintaining this :1st_place_medal: 

@DianaSuvorova thanks for your contributions! I've added you as a collaborator :100:

**Comment by burabure** [comment]
thanks @tlvince =)  and congrats @DianaSuvorova :tada:
