### ISSUE TITLE
Newline before expect is opt-out

### ISSUE THREAD

**Issue by cbgmc** [tlvince/eslint-plugin-jasmine#135]
**Do you want to request a *feature* or report a *bug*?**
Not sure, bug maybe?

**What is the current behavior?**
Newline before expect is opt-out

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Newline before expect is opt-in

**Please mention your node.js, eslint-plugin-jasmine and operating system version.**
node: 7.9.0
eslint-plugin-jasmine: Used to be ^2.2.0, now locked to 2.2.0
osx: 10.11.6
==============

My team uses the jasmine plugin and we suddenly noticed that eslint --fix was touching every Spec file in each project and adding newlines. Our specs tend to look something like this: http://i.imgur.com/bv9y2rM.png So now they're filled with whitespace. 

Can this rule be made opt-in instead of opt-out?

**Comment by DianaSuvorova** [comment]
Hi Mac,

Yes, this rule was added recently and it is on by default. You can disable this rule in your project configuration.

(  for example adding below line to `.eslintrc.json`):
```js
"jasmine/new-line-before-expect": 0
```

When the rule is off fixer will not apply the fix.

Sorry about this confusion.
-Diana
