### ISSUE TITLE
Detecting describe(function (done) { ... })

### ISSUE THREAD

**Issue by mik01aj** [tlvince/eslint-plugin-jasmine#14]
I originally reported an issue in Jasmine: https://github.com/jasmine/jasmine/issues/896 but now I think it would be actually more appropiate here.

> I spent half an hour debugging this.

>     describe('stuff', function (done) {
>         it('works good', function () {
>             myHttp.get(url).then(function (response) {
>                 expect(response.data.length).toBeGreaterThan(10000);
>             }).then(done, fail);
>         });
>     });

> I got an error in some other unrelated test, with no stacktrace (because async), and had to fire up a debugger to understand what's happening. And it was just a simple mistake.

> (In case you still didn't notice: I put `done` in `describe` instead of `it`.)

> I believe this wouldn't be hard to do (as you already look at the arguments of the function given in `it`) and would save other programmers from mistakes like this.

**Comment by tlvince** [comment]
Good idea.

Do you know if there's any case when passing a argument to `describe` is valid? (I've not seen one myself). Otherwise, we could simply test on `if (arguments.length) { return 'fail' }`.

**Comment by mik01aj** [comment]
It is, afaik, always invalid.
