### ISSUE TITLE
The prefer-toHaveBeenCalledWith rule name isn't consistent with other rule names.

### ISSUE THREAD

**Issue by jpickwell** [tlvince/eslint-plugin-jasmine#160]
Rule names should be snake-case to be consistent with ESLint rules. `prefer-toHaveBeenCalledWith` violates this consistency. It should instead be `prefer-to-have-been-called-with`.

**Comment by burabure** [comment]
in this case `toHaveBeenCalledWith` refers to a particular methodName so it's written verbatim. To be fair both rule namings would be correct.

**Comment by jpickwell** [comment]
I guess. This is the first time I've seen camel-case used in an ESLint rule and it not be corrected. Different experiences I guess.
