### ISSUE TITLE
expect-single-argument flags expect().nothing()

### ISSUE THREAD

**Issue by asapach** [tlvince/eslint-plugin-jasmine#176]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`expect().nothing()` is a valid statement, but is being reported by `expect-single-argument`:
> Expect must have a single argument. No arguments were provided. (jasmine/expect-single-argument)

**If the current behavior is a bug, please provide the steps to reproduce.**
Default `jasmine/recommended` settings.

**What is the expected behavior?**
[`expect().nothing()`](https://jasmine.github.io/api/edge/matchers.html#nothing) should not be treated as an error

**Please mention your node.js, eslint-plugin-jasmine and operating system version.**
Windows 10 x64
Node v8.14.0
eslint@5.12.0
eslint-plugin-jasmine@2.10.1

**Comment by raeffu** [comment]
I have the same problem.

**Comment by TimZM** [comment]
I also ran into this issue and opened a PR to fix this. Is this something that can be picked up @tlvince? This issue has been open since 2019
