### ISSUE TITLE
Add version to package.json

### ISSUE THREAD

**Issue by mastertinner** [tlvince/eslint-plugin-jasmine#18]
Please add the version property to package.json as specified in https://docs.npmjs.com/files/package.json#version

**Comment by tlvince** [comment]
I use [semantic-release](https://github.com/semantic-release/semantic-release) to publish this package, which explicitly removes the `version` property from the source, but restores during an npm release.

**Comment by mastertinner** [comment]
Sorry, I didn't know about that tool. Thanks for clarifying and for the quick reply!
