### ISSUE TITLE
Support ESLint 7.x

### ISSUE THREAD

**Issue by BePo65** [tlvince/eslint-plugin-jasmine#244]
ESLint [v7.0.0 ](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) is released .

It would be awesome to have official ESLint 7 support.

**Comment by lachieh** [comment]
Suggest changing the name of this to `Support ESLint 8.0`. Currently there are errors when using this package due to this change:
https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#fixes

**Comment by DamienCassou** [comment]
The latest (unreleased) version of eslint-plugin-jasmine works fine with eslint 8. I suggest closing this bug and [releasing a new version of eslint-plugin-jasmine](https://github.com/tlvince/eslint-plugin-jasmine/issues/342) instead.

In the meantime, you can

```
$ yarn add --dev eslint-plugin-jasmine@https://github.com/tlvince/eslint-plugin-jasmine.git#commit=3a61ff2ee9d82815d3f03ae61df8c75300f64838
```

(or the equivalent NPM command) to force using an unreleased version of the package.

**Comment by markusrisberg** [comment]
Are there any plans to support ESLint 9.0? 

https://eslint.org/docs/latest/use/migrate-to-9.0.0#-function-style-rules-are-no-longer-supported

**Comment by pozil** [comment]
In case this helps, here's a `eslint.config.js` that works with ESLint 9:

```
import js from '@eslint/js';
import jasmine from 'eslint-plugin-jasmine';
import globals from 'globals';

export default [
    js.configs.recommended,
    jasmine.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 13,
            globals: {
                ...globals.node,
                ...globals.jasmine
            }
        },
        plugins: {
            jasmine
        }
    }
];
```

**Comment by tlvince** [comment]
Closed by https://github.com/tlvince/eslint-plugin-jasmine/releases/tag/v4.2.0
