### ISSUE TITLE
No expect in beforeEach, afterEach, beforeAll and afterAll

### ISSUE THREAD

**Issue by alecxe** [tlvince/eslint-plugin-jasmine#28]
Would it make sense to prohibit the usage of `expect()` inside `beforeEach`, `afterEach`, `beforeAll` and `afterAll`?

If yes, I can work on making the PR. Thanks.

**Comment by burabure** [comment]
@alecxe is that valid jasmine?, I never seen something like that. Have you testetd out what happens if you put `expect``in those blocks?

**Comment by alecxe** [comment]
@burabure yeah, you can have `expect()` working in `beforeEach()` or other "setup", "teardown" functions.

**Comment by burabure** [comment]
@alecxe want to give it a go?, if you never worked with eslint rules before, it's a great learning experience. You can start here: http://eslint.org/docs/developer-guide/working-with-rules and also you'll need this https://astexplorer.net/

**Comment by alecxe** [comment]
@burabure sure, would be great, thanks.

**Comment by alecxe** [comment]
@burabure trying to think of a name for this rule..but I don't like any of the names: `valid-expect-location`, `expect-location`, `unexpected-expect`, `no-expect-in-setup-teardown`..ideas? Thanks.

**Comment by burabure** [comment]
`no-unexpected-expect` or `no-expect-in-setup-teardown` sound fine to me @alecxe

**Comment by alecxe** [comment]
Fixed by #105. Thanks.
