### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by DamienCassou** [tlvince/eslint-plugin-jasmine#342]
Some bugs have been fixed in master that prevented this package from running with eslint 8. I suggest releasing a new version of this package so everyone can upgrade to eslint 8 without problem.

**Comment by kshilnov** [comment]
Great idea

**Comment by dima716** [comment]
Yes, I confirm there are problems with using this plugin with eslint 8. Master branch has necessary fix.

**Comment by dima716** [comment]
@tlvince will you look at it, please?

**Comment by tlvince** [comment]
Done, thanks https://github.com/tlvince/eslint-plugin-jasmine/releases/tag/v4.1.3.

(Automated releases had stopped because of the Travis CI org shutdown. I've migrated it to Travis com.)
