### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by DamienCassou** [tlvince/eslint-plugin-jasmine#369]
The previous release is from 2021. With all the changes in eslint v9, is it time to release a new version of this plugin?

**Comment by DianaSuvorova** [comment]
I agree, I think only @tlvince can do releases

**Comment by tlvince** [comment]
Releases are automated via semantic-release, but were broken due to the TravisCI OSS saga a few years ago. I've just migrated CI to GitHub Actions. Would you mind testing [v4.1.4-beta.1](https://github.com/tlvince/eslint-plugin-jasmine/releases/tag/v4.1.4-beta.1) works with both ESLint v9 and v8?

**Comment by DamienCassou** [comment]
@tlvince: thank you very much for the quick action. I confirm that4.1.4-beta.1 works fine with eslint v8. Unfortunately, https://github.com/tlvince/eslint-plugin-jasmine/issues/371 prevents the release from working on eslint v9.

**Comment by tlvince** [comment]
[v4.2.0](https://github.com/tlvince/eslint-plugin-jasmine/releases/tag/v4.2.0) released. Thanks!
