### ISSUE TITLE
Some rules are incompatible with eslint v9 because they export a function

### ISSUE THREAD

**Issue by DamienCassou** [tlvince/eslint-plugin-jasmine#371]
[Function-style rules are no longer supported](https://eslint.org/docs/latest/use/migrate-to-9.0.0#-function-style-rules-are-no-longer-supported).

Problematic rules:
- expect-matcher
- expect-single-argument
- named-spy
- no-assign-spyon
- no-describe-variables
- no-disabled-tests
- no-focused-tests
- no-global-setup
- no-pending-tests
- no-suite-callback-args
- no-unsafe-spy
- prefer-jasmine-matcher
- prefer-toHaveBeenCalledWith
- valid-expect

**Comment by tlvince** [comment]
Thanks for raising. I believe these are fixed by #367 and #368. I've cherry picked those into [v4.1.4-beta.2](https://github.com/tlvince/eslint-plugin-jasmine/releases/tag/v4.1.4-beta.2). Would mind giving testing that? I assume this is a breaking change and requires eslint >=9.

**Comment by DamienCassou** [comment]
v4.1.4-beta.3 works for both eslint 8 old-style config file and eslint 9 flat config file. Thank you very much to everyone involved.

**Comment by tlvince** [comment]
Excellent! [v4.2.0](https://github.com/tlvince/eslint-plugin-jasmine/releases/tag/v4.2.0) released. Thanks!
