### ISSUE TITLE
Unable to install master version via github, last release seems somewhat out of date

### ISSUE THREAD

**Issue by robertfmurdock** [tlvince/eslint-plugin-jasmine#46]
The last version, 1.6, is giving me problems with current versions of eslint (can't find the rulesets). It looks like the master branch has changed since 1.6, though. I tried installing directly from github with NPM and that currently does not work (for me, anyway).

Sorry, that's a bit scatterbrained.

**Comment by robertfmurdock** [comment]
Just confirmed things work much better with the master version. Hoping the next version comes soon!

**Comment by tlvince** [comment]
[v1.7.0](https://github.com/tlvince/eslint-plugin-jasmine/releases/tag/v1.7.0) just landed.

**Comment by robertfmurdock** [comment]
Fantastic! I'll give it a look.
