### ISSUE TITLE
'describe' is not defined  no-undef error

### ISSUE THREAD

**Issue by triberraar** [tlvince/eslint-plugin-jasmine#56]
Hej,
This must be my lack of understanding, but when i add this plugin to my eslint configuration and run it i get these errors:

> 3:1  error  'describe' is not defined  no-undef
  4:5  error  'it' is not defined        no-undef
  5:9  error  'expect' is not defined    no-undef
  7:5  error  'it' is not defined        no-undef
  8:9  error  'expect' is not defined    no-undef

My .eslintrc looks like this:

```
{
  "plugins": ["jasmine"],
  "extends": ["angular", "eslint:recommended", "plugin:jasmine/recommended"],
  "rules": {
    "quotes": [ 2, "single"],
    "strict": [2, "global"],
    "semi": ["error", "always"],
    "angular/on-watch": "warn"
  }
}
```

And in my package.json i have version ^2.3.0 for eslint and ^1.8.1 for eslint-plugin-jasmin.

Any help/pointers are appreciated.

**Comment by tlvince** [comment]
I believe you're missing the [jasmine environment](http://eslint.org/docs/user-guide/configuring#specifying-environments) there. Try:

```json
{
  "plugins": ["jasmine"],
  "extends": ["angular", "eslint:recommended", "plugin:jasmine/recommended"],
  "rules": {
    "quotes": [ 2, "single"],
    "strict": [2, "global"],
    "semi": ["error", "always"],
    "angular/on-watch": "warn"
  },
  "env": {
    "jasmine": true
  }
}
```

**Comment by triberraar** [comment]
That is it, can't seem to find it in the readme or it is just my lack of understanding eslint.
