### ISSUE TITLE
Rule suggestion: no-tohavebeencalled

### ISSUE THREAD

**Issue by nicbou** [tlvince/eslint-plugin-jasmine#64]
toHaveBeenCalled should be replaced with toHaveBeenCalledWith to ensure that functions are properly called and receive the right arguments.

**Comment by burabure** [comment]
Agree, 99% of the time toHaveBeenCalledWith is the correct approach.

@nicbou want to give it a go?, if you never worked with eslint rules before, it's a great learning experience. You can start here: http://eslint.org/docs/developer-guide/working-with-rules and also you'll need this https://astexplorer.net/

**Comment by nicbou** [comment]
I'd love to help, but I first need to get buy-in for my colleagues, since they'll be the ones fighting against the linter.

**Comment by burabure** [comment]
@DianaSuvorova I think this is an important rule, do you have time by any chance to implement this?

**Comment by DianaSuvorova** [comment]
Will do :)
