### ISSUE TITLE
Add no-spec-dupes rule

### ISSUE THREAD

**Issue by tlvince** [tlvince/eslint-plugin-jasmine#8]
Following #7, we should add a rule that checks for duplicate specs (`it` blocks).

The guts of [no-suite-dupes](https://github.com/tlvince/eslint-plugin-jasmine/blob/19f5b656d968a00d9ce275a4914fefcf45d42a73/lib/rules/no-suite-dupes.js) should be extracted out into `lib` for reuse here.

**Comment by ArnaudRinquin** [comment]
I can take care of that one.
