### ISSUE TITLE
I'd love to help maintain this project

### ISSUE THREAD

**Issue by burabure** [tlvince/eslint-plugin-jasmine#93]
@tlvince didn't know where else to post this: I'd love to help maintain this project

**Comment by tlvince** [comment]
Hey @burabure thanks for the interest! I've added you as a collaborator.

I think a great place to start would be to update this to support ESLint v3; there are a number of [greenkeeper](https://greenkeeper.io) pull requests open which show it's failing the tests currently. Worth a look?

**Comment by michael-smith-tanium** [comment]
There is a tool now to convert to v3 rules -- http://eslint.org/blog/2016/07/eslint-new-rule-format#automatic-transformation
