### ISSUE TITLE
support node 4

### ISSUE THREAD

**Issue by kentor** [tlvince/eslint-plugin-jasmine#97]
#Hi,

I think this package should support node >= 4, not node >= 6, to be aligned with ESLint.

The 2.0.0 release notes were misleading. It says "This module no longer supports Node.js 0.10" but doesn't say it only supports node >= 6. This broke when installing with yarn on node 4 because yarn checks `engines` in `package.json`.

**Comment by tlvince** [comment]
Refs #96.
